### ISSUE TITLE
Multi-language support

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns-vuepress-web#3]
Vuepress.js default theme comes with great support for multilingual sites. In this issue let's configure the site so that it enables switching the language and browsing to pages produced in other languages.

**Comment by iluwatar** [comment]
Done for single language. The web site can now switch between English and Chinese. Other languages can be added similarly. Basically, the steps are

- Add a new locale to `config.js` and the necessary toolbar items for navigation
- Edit `build.sh` to move the markdown pages (patterns, principles, snippets) to correct location

**Comment by diegoborbamobiauto** [comment]
Can I contribute with a Portuguese translation?

**Comment by diegoborbadev** [comment]
Can I contribute with a Portuguese translation?

**Comment by iluwatar** [comment]
Sure! More languages are welcome. Create an issue for that and follow similar steps as here: https://github.com/iluwatar/java-design-patterns-vuepress-web/issues/27

**Comment by diegoborbadev** [comment]
Created #87
