### ISSUE TITLE
Theme button

### ISSUE THREAD

**Issue by GiulioBernardi** [iluwatar/java-design-patterns-vuepress-web#67]
The theme button is having a strange behaviour when clicked.
It looks like it initial state is the oposite one that is beeing applied to the website, and then when you change it, it does not apply any theme changes because theme is already applied.

Gif bellow
![button-state](https://github.com/iluwatar/java-design-patterns-vuepress-web/assets/54187661/2a446ce7-0222-4532-86da-858c4811708d)

**Comment by iluwatar** [comment]
I think the initial state is "automatic". It switches between light and dark modes based on the time of day. The other states are light and dark.

**Comment by GiulioBernardi** [comment]
Well. It makes sense now that you said about the time of day based behaviour.
